import React from "react";
import { Block } from "../common/Block";
import { Accordion } from "../common/Accordion";
import { UncheckList } from "../common/UncheckList";

const CheatsheetDataStructureAndAlgorithmComponent = () => {
  return (
    <>
      <Block title="💥 Topics To Be Noted Down:">
        <div>1. Steps To Implement Each Data Structure/Algorithm</div>
        <div>2. Dry Run Of Each Data Structure/Algorithm</div>
        <div>3. Advantage Of Each Data Structure/Algorithm</div>
        <div>4. Disadvantage Of Each Of The Data Structure/Algorithm</div>
        <div>5. Time Complexity Of Each Data Structure/Algorithm</div>
        <div>6. Space Complexity Of Each Data Structure/Algorithm</div>
        <div>7. When To Use Which Data Structure/Algorithm</div>
        <div>8. At Least Three Approach Of Each Problems</div>
      </Block>
      <Block title="❗ Important Resources:">
        <div>1. Apna College</div>
      </Block>
      <Accordion outer="Apna College Videos">
        <Accordion outer="Take Notes">
          <UncheckList>
            <div>Video No. 1</div>
            <div>Video No. 2</div>
            <div>Video No. 3</div>
            <div>Video No. 4</div>
            <div>Video No. 5</div>
            <div>Video No. 6</div>
            <div>Video No. 7</div>
            <div>Video No. 8</div>
            <div>Video No. 9</div>
            <div>Video No. 10</div>
            <div>Video No. 11</div>
            <div>Video No. 12</div>
            <div>Video No. 13</div>
            <div>Video No. 14</div>
            <div>Video No. 15</div>
            <div>Video No. 16</div>
            <div>Video No. 17</div>
            <div>Video No. 18</div>
            <div>Video No. 19</div>
            <div>Video No. 20</div>
            <div>Video No. 21</div>
            <div>Video No. 22</div>
            <div>Video No. 23</div>
            <div>Video No. 24</div>
            <div>Video No. 25</div>
            <div>Video No. 26</div>
            <div>Video No. 27</div>
            <div>Video No. 28</div>
            <div>Video No. 29</div>
            <div>Video No. 30</div>
            <div>Video No. 31</div>
            <div>Video No. 32</div>
            <div>Video No. 33</div>
            <div>Video No. 34</div>
            <div>Video No. 35</div>
            <div>Video No. 36</div>
            <div>Video No. 37</div>
            <div>Video No. 38</div>
            <div>Video No. 39</div>
            <div>Video No. 40</div>
            <div>Video No. 41</div>
            <div>Video No. 42</div>
            <div>Video No. 43</div>
            <div>Video No. 44</div>
            <div>Video No. 45</div>
            <div>Video No. 46</div>
            <div>Video No. 47</div>
            <div>Video No. 48</div>
            <div>Video No. 49</div>
            <div>Video No. 50</div>
            <div>Video No. 51</div>
            <div>Video No. 52</div>
            <div>Video No. 53</div>
            <div>Video No. 54</div>
            <div>Video No. 55</div>
            <div>Video No. 56</div>
            <div>Video No. 57</div>
            <div>Video No. 58</div>
            <div>Video No. 59</div>
            <div>Video No. 60</div>
            <div>Video No. 61</div>
            <div>Video No. 62</div>
            <div>Video No. 63</div>
            <div>Video No. 64</div>
            <div>Video No. 65</div>
            <div>Video No. 66</div>
            <div>Video No. 67</div>
            <div>Video No. 68</div>
            <div>Video No. 69</div>
            <div>Video No. 70</div>
            <div>Video No. 71</div>
            <div>Video No. 72</div>
            <div>Video No. 73</div>
            <div>Video No. 74</div>
            <div>Video No. 75</div>
            <div>Video No. 76</div>
            <div>Video No. 77</div>
            <div>Video No. 78</div>
            <div>Video No. 79</div>
            <div>Video No. 80</div>
            <div>Video No. 81</div>
            <div>Video No. 82</div>
            <div>Video No. 83</div>
            <div>Video No. 84</div>
            <div>Video No. 85</div>
            <div>Video No. 86</div>
            <div>Video No. 87</div>
            <div>Video No. 88</div>
            <div>Video No. 89</div>
            <div>Video No. 90</div>
            <div>Video No. 91</div>
            <div>Video No. 92</div>
            <div>Video No. 93</div>
            <div>Video No. 94</div>
            <div>Video No. 95</div>
            <div>Video No. 96</div>
            <div>Video No. 97</div>
            <div>Video No. 98</div>
            <div>Video No. 99</div>
            <div>Video No. 100</div>
            <div>Video No. 101</div>
            <div>Video No. 102</div>
            <div>Video No. 103</div>
            <div>Video No. 104</div>
            <div>Video No. 105</div>
            <div>Video No. 106</div>
            <div>Video No. 107</div>
            <div>Video No. 108</div>
            <div>Video No. 109</div>
            <div>Video No. 110</div>
            <div>Video No. 111</div>
            <div>Video No. 112</div>
            <div>Video No. 113</div>
            <div>Video No. 114</div>
            <div>Video No. 115</div>
            <div>Video No. 116</div>
            <div>Video No. 117</div>
            <div>Video No. 118</div>
            <div>Video No. 119</div>
            <div>Video No. 120</div>
            <div>Video No. 121</div>
            <div>Video No. 122</div>
            <div>Video No. 123</div>
            <div>Video No. 124</div>
            <div>Video No. 125</div>
            <div>Video No. 126</div>
            <div>Video No. 127</div>
            <div>Video No. 128</div>
            <div>Video No. 129</div>
            <div>Video No. 130</div>
            <div>Video No. 131</div>
            <div>Video No. 132</div>
            <div>Video No. 133</div>
            <div>Video No. 134</div>
            <div>Video No. 135</div>
            <div>Video No. 136</div>
            <div>Video No. 137</div>
            <div>Video No. 138</div>
            <div>Video No. 139</div>
            <div>Video No. 140</div>
            <div>Video No. 141</div>
            <div>Video No. 142</div>
            <div>Video No. 143</div>
            <div>Video No. 144</div>
            <div>Video No. 145</div>
            <div>Video No. 146</div>
            <div>Video No. 147</div>
            <div>Video No. 148</div>
            <div>Video No. 149</div>
            <div>Video No. 150</div>
            <div>Video No. 151</div>
            <div>Video No. 152</div>
            <div>Video No. 153</div>
            <div>Video No. 154</div>
            <div>Video No. 155</div>
            <div>Video No. 156</div>
            <div>Video No. 157</div>
            <div>Video No. 158</div>
            <div>Video No. 159</div>
            <div>Video No. 160</div>
            <div>Video No. 161</div>
            <div>Video No. 162</div>
            <div>Video No. 163</div>
            <div>Video No. 164</div>
            <div>Video No. 165</div>
            <div>Video No. 166</div>
            <div>Video No. 167</div>
            <div>Video No. 168</div>
            <div>Video No. 169</div>
            <div>Video No. 170</div>
            <div>Video No. 171</div>
            <div>Video No. 172</div>
            <div>Video No. 173</div>
            <div>Video No. 174</div>
            <div>Video No. 175</div>
            <div>Video No. 176</div>
            <div>Video No. 177</div>
            <div>Video No. 178</div>
            <div>Video No. 179</div>
            <div>Video No. 180</div>
            <div>Video No. 181</div>
            <div>Video No. 182</div>
            <div>Video No. 183</div>
            <div>Video No. 184</div>
            <div>Video No. 185</div>
            <div>Video No. 186</div>
            <div>Video No. 187</div>
            <div>Video No. 188</div>
            <div>Video No. 189</div>
            <div>Video No. 190</div>
            <div>Video No. 191</div>
            <div>Video No. 192</div>
            <div>Video No. 193</div>
            <div>Video No. 194</div>
            <div>Video No. 195</div>
            <div>Video No. 196</div>
            <div>Video No. 197</div>
            <div>Video No. 198</div>
            <div>Video No. 199</div>
            <div>Video No. 200</div>
            <div>Video No. 201</div>
            <div>Video No. 202</div>
            <div>Video No. 203</div>
            <div>Video No. 204</div>
            <div>Video No. 205</div>
            <div>Video No. 206</div>
            <div>Video No. 207</div>
            <div>Video No. 208</div>
            <div>Video No. 209</div>
            <div>Video No. 210</div>
            <div>Video No. 211</div>
            <div>Video No. 212</div>
            <div>Video No. 213</div>
            <div>Video No. 214</div>
            <div>Video No. 215</div>
            <div>Video No. 216</div>
            <div>Video No. 217</div>
            <div>Video No. 218</div>
            <div>Video No. 219</div>
            <div>Video No. 220</div>
            <div>Video No. 221</div>
          </UncheckList>
        </Accordion>
        <Accordion outer="Take Pictures And Organize">
          <UncheckList>
            <div>Video No. 1</div>
            <div>Video No. 2</div>
            <div>Video No. 3</div>
            <div>Video No. 4</div>
            <div>Video No. 5</div>
            <div>Video No. 6</div>
            <div>Video No. 7</div>
            <div>Video No. 8</div>
            <div>Video No. 9</div>
            <div>Video No. 10</div>
            <div>Video No. 11</div>
            <div>Video No. 12</div>
            <div>Video No. 13</div>
            <div>Video No. 14</div>
            <div>Video No. 15</div>
            <div>Video No. 16</div>
            <div>Video No. 17</div>
            <div>Video No. 18</div>
            <div>Video No. 19</div>
            <div>Video No. 20</div>
            <div>Video No. 21</div>
            <div>Video No. 22</div>
            <div>Video No. 23</div>
            <div>Video No. 24</div>
            <div>Video No. 25</div>
            <div>Video No. 26</div>
            <div>Video No. 27</div>
            <div>Video No. 28</div>
            <div>Video No. 29</div>
            <div>Video No. 30</div>
            <div>Video No. 31</div>
            <div>Video No. 32</div>
            <div>Video No. 33</div>
            <div>Video No. 34</div>
            <div>Video No. 35</div>
            <div>Video No. 36</div>
            <div>Video No. 37</div>
            <div>Video No. 38</div>
            <div>Video No. 39</div>
            <div>Video No. 40</div>
            <div>Video No. 41</div>
            <div>Video No. 42</div>
            <div>Video No. 43</div>
            <div>Video No. 44</div>
            <div>Video No. 45</div>
            <div>Video No. 46</div>
            <div>Video No. 47</div>
            <div>Video No. 48</div>
            <div>Video No. 49</div>
            <div>Video No. 50</div>
            <div>Video No. 51</div>
            <div>Video No. 52</div>
            <div>Video No. 53</div>
            <div>Video No. 54</div>
            <div>Video No. 55</div>
            <div>Video No. 56</div>
            <div>Video No. 57</div>
            <div>Video No. 58</div>
            <div>Video No. 59</div>
            <div>Video No. 60</div>
            <div>Video No. 61</div>
            <div>Video No. 62</div>
            <div>Video No. 63</div>
            <div>Video No. 64</div>
            <div>Video No. 65</div>
            <div>Video No. 66</div>
            <div>Video No. 67</div>
            <div>Video No. 68</div>
            <div>Video No. 69</div>
            <div>Video No. 70</div>
            <div>Video No. 71</div>
            <div>Video No. 72</div>
            <div>Video No. 73</div>
            <div>Video No. 74</div>
            <div>Video No. 75</div>
            <div>Video No. 76</div>
            <div>Video No. 77</div>
            <div>Video No. 78</div>
            <div>Video No. 79</div>
            <div>Video No. 80</div>
            <div>Video No. 81</div>
            <div>Video No. 82</div>
            <div>Video No. 83</div>
            <div>Video No. 84</div>
            <div>Video No. 85</div>
            <div>Video No. 86</div>
            <div>Video No. 87</div>
            <div>Video No. 88</div>
            <div>Video No. 89</div>
            <div>Video No. 90</div>
            <div>Video No. 91</div>
            <div>Video No. 92</div>
            <div>Video No. 93</div>
            <div>Video No. 94</div>
            <div>Video No. 95</div>
            <div>Video No. 96</div>
            <div>Video No. 97</div>
            <div>Video No. 98</div>
            <div>Video No. 99</div>
            <div>Video No. 100</div>
            <div>Video No. 101</div>
            <div>Video No. 102</div>
            <div>Video No. 103</div>
            <div>Video No. 104</div>
            <div>Video No. 105</div>
            <div>Video No. 106</div>
            <div>Video No. 107</div>
            <div>Video No. 108</div>
            <div>Video No. 109</div>
            <div>Video No. 110</div>
            <div>Video No. 111</div>
            <div>Video No. 112</div>
            <div>Video No. 113</div>
            <div>Video No. 114</div>
            <div>Video No. 115</div>
            <div>Video No. 116</div>
            <div>Video No. 117</div>
            <div>Video No. 118</div>
            <div>Video No. 119</div>
            <div>Video No. 120</div>
            <div>Video No. 121</div>
            <div>Video No. 122</div>
            <div>Video No. 123</div>
            <div>Video No. 124</div>
            <div>Video No. 125</div>
            <div>Video No. 126</div>
            <div>Video No. 127</div>
            <div>Video No. 128</div>
            <div>Video No. 129</div>
            <div>Video No. 130</div>
            <div>Video No. 131</div>
            <div>Video No. 132</div>
            <div>Video No. 133</div>
            <div>Video No. 134</div>
            <div>Video No. 135</div>
            <div>Video No. 136</div>
            <div>Video No. 137</div>
            <div>Video No. 138</div>
            <div>Video No. 139</div>
            <div>Video No. 140</div>
            <div>Video No. 141</div>
            <div>Video No. 142</div>
            <div>Video No. 143</div>
            <div>Video No. 144</div>
            <div>Video No. 145</div>
            <div>Video No. 146</div>
            <div>Video No. 147</div>
            <div>Video No. 148</div>
            <div>Video No. 149</div>
            <div>Video No. 150</div>
            <div>Video No. 151</div>
            <div>Video No. 152</div>
            <div>Video No. 153</div>
            <div>Video No. 154</div>
            <div>Video No. 155</div>
            <div>Video No. 156</div>
            <div>Video No. 157</div>
            <div>Video No. 158</div>
            <div>Video No. 159</div>
            <div>Video No. 160</div>
            <div>Video No. 161</div>
            <div>Video No. 162</div>
            <div>Video No. 163</div>
            <div>Video No. 164</div>
            <div>Video No. 165</div>
            <div>Video No. 166</div>
            <div>Video No. 167</div>
            <div>Video No. 168</div>
            <div>Video No. 169</div>
            <div>Video No. 170</div>
            <div>Video No. 171</div>
            <div>Video No. 172</div>
            <div>Video No. 173</div>
            <div>Video No. 174</div>
            <div>Video No. 175</div>
            <div>Video No. 176</div>
            <div>Video No. 177</div>
            <div>Video No. 178</div>
            <div>Video No. 179</div>
            <div>Video No. 180</div>
            <div>Video No. 181</div>
            <div>Video No. 182</div>
            <div>Video No. 183</div>
            <div>Video No. 184</div>
            <div>Video No. 185</div>
            <div>Video No. 186</div>
            <div>Video No. 187</div>
            <div>Video No. 188</div>
            <div>Video No. 189</div>
            <div>Video No. 190</div>
            <div>Video No. 191</div>
            <div>Video No. 192</div>
            <div>Video No. 193</div>
            <div>Video No. 194</div>
            <div>Video No. 195</div>
            <div>Video No. 196</div>
            <div>Video No. 197</div>
            <div>Video No. 198</div>
            <div>Video No. 199</div>
            <div>Video No. 200</div>
            <div>Video No. 201</div>
            <div>Video No. 202</div>
            <div>Video No. 203</div>
            <div>Video No. 204</div>
            <div>Video No. 205</div>
            <div>Video No. 206</div>
            <div>Video No. 207</div>
            <div>Video No. 208</div>
            <div>Video No. 209</div>
            <div>Video No. 210</div>
            <div>Video No. 211</div>
            <div>Video No. 212</div>
            <div>Video No. 213</div>
            <div>Video No. 214</div>
            <div>Video No. 215</div>
            <div>Video No. 216</div>
            <div>Video No. 217</div>
            <div>Video No. 218</div>
            <div>Video No. 219</div>
            <div>Video No. 220</div>
            <div>Video No. 221</div>
          </UncheckList>
        </Accordion>
        <Accordion outer="Store Everything">
          <UncheckList>
            <div>Video No. 1</div>
            <div>Video No. 2</div>
            <div>Video No. 3</div>
            <div>Video No. 4</div>
            <div>Video No. 5</div>
            <div>Video No. 6</div>
            <div>Video No. 7</div>
            <div>Video No. 8</div>
            <div>Video No. 9</div>
            <div>Video No. 10</div>
            <div>Video No. 11</div>
            <div>Video No. 12</div>
            <div>Video No. 13</div>
            <div>Video No. 14</div>
            <div>Video No. 15</div>
            <div>Video No. 16</div>
            <div>Video No. 17</div>
            <div>Video No. 18</div>
            <div>Video No. 19</div>
            <div>Video No. 20</div>
            <div>Video No. 21</div>
            <div>Video No. 22</div>
            <div>Video No. 23</div>
            <div>Video No. 24</div>
            <div>Video No. 25</div>
            <div>Video No. 26</div>
            <div>Video No. 27</div>
            <div>Video No. 28</div>
            <div>Video No. 29</div>
            <div>Video No. 30</div>
            <div>Video No. 31</div>
            <div>Video No. 32</div>
            <div>Video No. 33</div>
            <div>Video No. 34</div>
            <div>Video No. 35</div>
            <div>Video No. 36</div>
            <div>Video No. 37</div>
            <div>Video No. 38</div>
            <div>Video No. 39</div>
            <div>Video No. 40</div>
            <div>Video No. 41</div>
            <div>Video No. 42</div>
            <div>Video No. 43</div>
            <div>Video No. 44</div>
            <div>Video No. 45</div>
            <div>Video No. 46</div>
            <div>Video No. 47</div>
            <div>Video No. 48</div>
            <div>Video No. 49</div>
            <div>Video No. 50</div>
            <div>Video No. 51</div>
            <div>Video No. 52</div>
            <div>Video No. 53</div>
            <div>Video No. 54</div>
            <div>Video No. 55</div>
            <div>Video No. 56</div>
            <div>Video No. 57</div>
            <div>Video No. 58</div>
            <div>Video No. 59</div>
            <div>Video No. 60</div>
            <div>Video No. 61</div>
            <div>Video No. 62</div>
            <div>Video No. 63</div>
            <div>Video No. 64</div>
            <div>Video No. 65</div>
            <div>Video No. 66</div>
            <div>Video No. 67</div>
            <div>Video No. 68</div>
            <div>Video No. 69</div>
            <div>Video No. 70</div>
            <div>Video No. 71</div>
            <div>Video No. 72</div>
            <div>Video No. 73</div>
            <div>Video No. 74</div>
            <div>Video No. 75</div>
            <div>Video No. 76</div>
            <div>Video No. 77</div>
            <div>Video No. 78</div>
            <div>Video No. 79</div>
            <div>Video No. 80</div>
            <div>Video No. 81</div>
            <div>Video No. 82</div>
            <div>Video No. 83</div>
            <div>Video No. 84</div>
            <div>Video No. 85</div>
            <div>Video No. 86</div>
            <div>Video No. 87</div>
            <div>Video No. 88</div>
            <div>Video No. 89</div>
            <div>Video No. 90</div>
            <div>Video No. 91</div>
            <div>Video No. 92</div>
            <div>Video No. 93</div>
            <div>Video No. 94</div>
            <div>Video No. 95</div>
            <div>Video No. 96</div>
            <div>Video No. 97</div>
            <div>Video No. 98</div>
            <div>Video No. 99</div>
            <div>Video No. 100</div>
            <div>Video No. 101</div>
            <div>Video No. 102</div>
            <div>Video No. 103</div>
            <div>Video No. 104</div>
            <div>Video No. 105</div>
            <div>Video No. 106</div>
            <div>Video No. 107</div>
            <div>Video No. 108</div>
            <div>Video No. 109</div>
            <div>Video No. 110</div>
            <div>Video No. 111</div>
            <div>Video No. 112</div>
            <div>Video No. 113</div>
            <div>Video No. 114</div>
            <div>Video No. 115</div>
            <div>Video No. 116</div>
            <div>Video No. 117</div>
            <div>Video No. 118</div>
            <div>Video No. 119</div>
            <div>Video No. 120</div>
            <div>Video No. 121</div>
            <div>Video No. 122</div>
            <div>Video No. 123</div>
            <div>Video No. 124</div>
            <div>Video No. 125</div>
            <div>Video No. 126</div>
            <div>Video No. 127</div>
            <div>Video No. 128</div>
            <div>Video No. 129</div>
            <div>Video No. 130</div>
            <div>Video No. 131</div>
            <div>Video No. 132</div>
            <div>Video No. 133</div>
            <div>Video No. 134</div>
            <div>Video No. 135</div>
            <div>Video No. 136</div>
            <div>Video No. 137</div>
            <div>Video No. 138</div>
            <div>Video No. 139</div>
            <div>Video No. 140</div>
            <div>Video No. 141</div>
            <div>Video No. 142</div>
            <div>Video No. 143</div>
            <div>Video No. 144</div>
            <div>Video No. 145</div>
            <div>Video No. 146</div>
            <div>Video No. 147</div>
            <div>Video No. 148</div>
            <div>Video No. 149</div>
            <div>Video No. 150</div>
            <div>Video No. 151</div>
            <div>Video No. 152</div>
            <div>Video No. 153</div>
            <div>Video No. 154</div>
            <div>Video No. 155</div>
            <div>Video No. 156</div>
            <div>Video No. 157</div>
            <div>Video No. 158</div>
            <div>Video No. 159</div>
            <div>Video No. 160</div>
            <div>Video No. 161</div>
            <div>Video No. 162</div>
            <div>Video No. 163</div>
            <div>Video No. 164</div>
            <div>Video No. 165</div>
            <div>Video No. 166</div>
            <div>Video No. 167</div>
            <div>Video No. 168</div>
            <div>Video No. 169</div>
            <div>Video No. 170</div>
            <div>Video No. 171</div>
            <div>Video No. 172</div>
            <div>Video No. 173</div>
            <div>Video No. 174</div>
            <div>Video No. 175</div>
            <div>Video No. 176</div>
            <div>Video No. 177</div>
            <div>Video No. 178</div>
            <div>Video No. 179</div>
            <div>Video No. 180</div>
            <div>Video No. 181</div>
            <div>Video No. 182</div>
            <div>Video No. 183</div>
            <div>Video No. 184</div>
            <div>Video No. 185</div>
            <div>Video No. 186</div>
            <div>Video No. 187</div>
            <div>Video No. 188</div>
            <div>Video No. 189</div>
            <div>Video No. 190</div>
            <div>Video No. 191</div>
            <div>Video No. 192</div>
            <div>Video No. 193</div>
            <div>Video No. 194</div>
            <div>Video No. 195</div>
            <div>Video No. 196</div>
            <div>Video No. 197</div>
            <div>Video No. 198</div>
            <div>Video No. 199</div>
            <div>Video No. 200</div>
            <div>Video No. 201</div>
            <div>Video No. 202</div>
            <div>Video No. 203</div>
            <div>Video No. 204</div>
            <div>Video No. 205</div>
            <div>Video No. 206</div>
            <div>Video No. 207</div>
            <div>Video No. 208</div>
            <div>Video No. 209</div>
            <div>Video No. 210</div>
            <div>Video No. 211</div>
            <div>Video No. 212</div>
            <div>Video No. 213</div>
            <div>Video No. 214</div>
            <div>Video No. 215</div>
            <div>Video No. 216</div>
            <div>Video No. 217</div>
            <div>Video No. 218</div>
            <div>Video No. 219</div>
            <div>Video No. 220</div>
            <div>Video No. 221</div>
          </UncheckList>
        </Accordion>
      </Accordion>
    </>
  );
};

export const CheatsheetDataStructureAndAlgorithm = React.memo(CheatsheetDataStructureAndAlgorithmComponent);
